### ISSUE TITLE
Request: Add Fusion 360 Archive File(s) to Repo

### ISSUE THREAD

**Issue by shadow651** [JeremySCook/DustCollector-DC0#1]
This looks great!
I saw in the YouTube video you are using Fusion 360 for the design, would it be possible for you to add that projects archive file to this repository? Would make it a lot easier to modify the design for different machines/vacuums 

Here's the help article on how to export the fusion 360 files.
https://knowledge.autodesk.com/support/fusion-360/troubleshooting/caas/sfdcarticles/sfdcarticles/How-to-make-a-local-archive-back-up-file-in-Fusion-360.html

**Comment by chrisprolsm** [comment]
I would second @shadow651 in this request.
I'm new to fusion 360 and it would be nice to be able to modify it for my Bosch Colt rather than start from scratch (though I started Lars videos and so eager to start with a real life mini project).
Anyhow, thanks a lot for making this model and sharing it !
